# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-05-18 06:36
from __future__ import unicode_literals

from django.db import migrations, models
import spirit.user.models


class Migration(migrations.Migration):

    dependencies = [
        ('spirit_user', '0013_auto_20180518_1419'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='image',
            field=models.ImageField(default='image/default.png', storage=spirit.user.models.OverwriteStorage(), upload_to=spirit.user.models.upload_article_cover),
        ),
    ]
